spring:
  application:
    name: gateway-service-zuul



zuul:
  routes:
    workflowMgr:
      path: /workflow/**
      serviceId: usercenter_workflow
    systemMgr:
      path: /microservice/**
      serviceId: usercenter_microservice
    messageMgr:
      path: /mq/**
      serviceId: usercenter_mq
    ssoMgr:
      path: /sso/**
      serviceId: usercenter_sso


#eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.1.199:9999/eureka/