spring:
  application:
    name: gateway-service-zuul



zuul:
  routes:
    workflowMgr:
      path: /workflow/**
      serviceId: usercenter_workflow
    systemMgr:
      path: /microservice/**
      serviceId: usercenter_microservice
    messageMgr:
      path: /mq/**
      serviceId: usercenter_mq
    ssoMgr:
      path: /sso/**
      serviceId: usercenter_sso
  host:
    connect-timeout-millis: 65000
    socket-timeout-millis: 65000


#eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka/
      
      
ribbon:
  ReadTimeout: 60000
  SocketTimeout: 60000
  
  
  
  
server:
  tomcat:
    accept-count: 5000 
    max-threads: 5000
    max-connections: 5000
    
hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 60000
  threadpool:  
    default:  
      coreSize: 5000 